  - name: Commit configuration to repository (Gitea)
    ansible.builtin.shell: |
      git config --global user.email "{{ git_email }}"
      git config --global user.name "{{ git_user }}"
      git pull
      git add .
      git commit -m "{{ git_message }}"
      git -c http.sslVerify=false push --repo="{{ git_repository | urlsplit("scheme")}}://{{ lookup('env','GITEA_USERNAME') }}:{{ lookup('env','GITEA_PASSWORD') }}@{{ git_repository | urlsplit("hostname") }}{{ git_repository | urlsplit('path') }}"
    args:
      chdir: "{{ git_directory }}"
    ignore_errors: true
    register: git_result
    when: git_key_path is not defined

  - name: Commit configuration to repository (RSA Key)
    ansible.builtin.shell: |
      echo "$PRIVATE_KEY" > /tmp/temp_key
      chmod 600 /tmp/temp_key
      eval $(ssh-agent -s)
      ssh-add "{{ git_key_path }}"
      git config --global user.email "{{ git_email }}"
      git config --global user.name "{{ git_user }}"
      git pull
      git add .
      git -c http.sslVerify=false commit -m "{{ git_message }}"
      git push "{{ git_repository }}"
    args:
      chdir: "{{ git_directory }}"
    ignore_errors: true
    register: git_result
    when: git_key_path is defined
